/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Equipment3D: typeof import('./components/three/Equipment3D.vue')['default']
    GradientButton: typeof import('./components/ui/GradientButton.vue')['default']
    GradientCard: typeof import('./components/ui/GradientCard.vue')['default']
    GradientCheckbox: typeof import('./components/ui/GradientCheckbox.vue')['default']
    GradientInput: typeof import('./components/ui/GradientInput.vue')['default']
    GradientLoader: typeof import('./components/ui/GradientLoader.vue')['default']
    GradientModal: typeof import('./components/ui/GradientModal.vue')['default']
    GradientToggle: typeof import('./components/ui/GradientToggle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
